# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('welcome_heading', models.CharField(default=b'Hello!', help_text=b'Welcome Heading', max_length=45)),
                ('welcome_paragraph', models.CharField(default=b"Welcome, here's your first paragraph...", help_text=b'Welcome Paragraph', max_length=450)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
            bases=('pages.page',),
        ),
    ]
