# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('woodcraft_theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('caption_heading', models.CharField(default=b'Blurb for this featured image goes here.', max_length=60)),
                ('caption_blurb', models.CharField(default=b'Blurb for this featured image goes here.', max_length=100)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='woodcraft_theme.HomePage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
    ]
